
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("data_customer/new", "Create data_customer")) ?>
</div>

<?php echo $this->tag->form(array("data_customer/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search data_customer</h1>
</div>

<table>
    
    <tr>
        <td align="right">
            <label for="nama_pemesan">Nama</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_pemesan", "size" => 30)) ?>
        </td>
    </tr>
    

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
