
<?php echo $this->tag->form("data_customer/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("data_customer", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create data_customer</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="nama_pemesan">Nama</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_pemesan", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="alamat">Alamat</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("alamat", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="kabupaten">Kabupaten</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("kabupaten", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="no_tlp">Notlp</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("no_tlp", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
