<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("data_customer/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("data_customer/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nama</th>
            <th>Alamat</th>
            <th>Kabupaten</th>
            <th>Notlp</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $data_customer) { ?>
        <tr>
            <td><?php echo $data_customer->_id ?></td>
            <td><?php echo $data_customer->nama_pemesan ?></td>
            <td><?php echo $data_customer->alamat ?></td>
            <td><?php echo $data_customer->kabupaten ?></td>
            <td><?php echo $data_customer->no_tlp ?></td>
            <td><?php echo $this->tag->linkTo(array("data_customer/edit/" . $data_customer->_id, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("data_customer/delete/" . $data_customer->_id, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("data_customer/search", "First") ?></td>
                        <td><?php echo $this->tag->linkTo("data_customer/search?page=" . $page->before, "Previous") ?></td>
                        <td><?php echo $this->tag->linkTo("data_customer/search?page=" . $page->next, "Next") ?></td>
                        <td><?php echo $this->tag->linkTo("data_customer/search?page=" . $page->last, "Last") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
