<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>

<table width="100%">
    <tr>
        <td align="left">
            <?php echo $this->tag->linkTo(array("data_customer/index", "Go Back")); ?>
        </td>
        <td align="right">
            <?php echo $this->tag->linkTo(array("data_customer/new", "Create ")); ?>
        </td>
    </tr>
</table>

<table class="browse" align="center">
    <thead>
        <tr>
            <th>Id</th>
            <th>Kode</th>
            <th>Nama</th>
            <th>Alamat</th>
            <th>Kabupaten</th>
            <th>Notlp</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($item as $data) { ?>
        <tr>
            <td><?php echo $data->_id ?></td>
            <td><?php echo $data->kode_pemesan ?></td>
            <td><?php echo $data->nama_pemesan ?></td>
            <td><?php echo $data->alamat ?></td>
            <td><?php echo $data->kabupaten ?></td>
            <td><?php echo $data->no_tlp ?></td>
            <td><?php echo $this->tag->linkTo(array("data_customer/edit/" . $data->kode_pemesan, "Edit")); ?></td>
            <td><?php echo $this->tag->linkTo(array("data_customer/delete/" . $data->kode_pemesan, "Delete")); ?></td>
        </tr>
    <?php } ?>
    </tbody>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    
                </table>
            </td>
        </tr>
    </tbody>
</table>
