
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("data_ongkir/save") ?>

<div align="center">
    <h1>Edit Ongkir</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="kode_daerah">Kode Daerah</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("kode_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nama_daerah">Nama Daerah</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ongkir">Ongkir</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ongkir", "size" => 30)) ?>
        </td>
    </tr>
        
    <tr>
        <td><?php echo $this->tag->hiddenField("_id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
