
<?php echo $this->tag->form("data_ongkir/create") ?>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Ongkir</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="kode_daerah">Kode Daerah</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("kode_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nama_daerah">Nama Daerah</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_daerah", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="ongkir">Ongkos Kirim</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("ongkir", "size" => 30)) ?>
        </td>
    </tr>
        
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
