
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("data_kendaraan/save") ?>

<div align="center">
    <h1>Edit Kendaraan</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="plat_nomor">Nomor Plat</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("plat_nomor", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="jenis_kendaraan">Jenis Kendaraan</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("jenis_kendaraan", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nomor_stnk">Nomor STNK</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nomor_stnk", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="kapasitas">Kapasitas</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("kapasitas", "size" => 30)) ?>
        </td>
    </tr>
    
    <tr>
        <td><?php echo $this->tag->hiddenField("_id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
