
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("data_kendaraan/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("data_kendaraan", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit data_kendaraan</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="plat_nomor">Nomor Plat</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("plat_nomor", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="jenis_kendaraan">jenis_kendaraan</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("jenis_kendaraan", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nomor_stnk">nomor_stnk</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nomor_stnk", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="kapasitas">kapasitas</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("kapasitas", "size" => 30)) ?>
        </td>
    </tr>
    
    <tr>
        <td><?php echo $this->tag->hiddenField("_id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
