
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("data_kendaraan/new", "Create data_kendaraan")) ?>
</div>

<?php echo $this->tag->form(array("data_kendaraan/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search data_kendaraan</h1>
</div>

<table>
    
    <tr>
        <td align="right">
            <label for="plat_nomor">Nomor Pla</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("plat_nomor", "size" => 30)) ?>
        </td>
    </tr>
    

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
