
<?php echo $this->tag->form("data_pemesanan/create") ?>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create Pemesan</h1>
</div>
<script>
function myFunction(e)
{
     if (e.keyCode == 13) {
        var t = document.getElementById("daerah");
var selectedText = t.options[t.selectedIndex].text;
var td = document.getElementById("berat");
var berat = td.value;

var yourString = selectedText.replace ( /[^\d.]/g, '' );
var total = berat * yourString;
document.getElementById("total").value=total;

return false;
}


}
</script>
<table>
    <tr>
        <td align="right">
            <label for="kode_pemesanan">Kode Pemesanan</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("kode_pemesanan", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nama_pemesan">Nama Pemesan</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("nama_pemesan", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="nama_daerah">Nama Daerah</label>
        </td>
        <td align="left">
           <select id="daerah" name="nama_daerah">
                <option value="@">Please, choose one..</option>
                <?php foreach ($item as $data) { ?>
                <option value="<?php echo $data->nama_daerah ?>"><?php echo $data->nama_daerah ?>-<?php echo $data->ongkir ?></option>
                <?php } ?>
            </select>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="berat_barang">Berat Barang</label>
        </td>
        <td align="left">
             <input type="text" id="berat" name="berat_barang" size="30" onkeypress="return myFunction(event)">
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="total_ongkir">Total Ongkir</label>
        </td>
        <td align="left">
            <input type="text" id="total" name="total_ongkir" size="30">
        </td>
    </tr>
        
    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
